### ISSUE TITLE
AI alt description generation

### ISSUE THREAD

**Issue by Truhe2342** [VernissageApp/Vernissage#103]
IceCubes added this using OpenAI and it would be very helpful to also have this in Vernissage.

When editing the image description you can generate a description.

<img width="375" alt="image" src="https://github.com/VernissageApp/Vernissage/assets/118095316/e11fa9d4-88b4-439a-b6e8-ab1d1131281b">

![image](https://github.com/VernissageApp/Vernissage/assets/118095316/36b531ea-b7cc-4ca5-ba05-c173714b01e5)

**Comment by mczachurski** [comment]
The generation of photo descriptions using AI is an intriguing feature. However, I would like to have greater control over how these texts are generated. This necessitates adding new functionalities on the API side to enable the remote activation/deactivation of this feature for individual users. At present, I do not have the resources to implement such functionality in the Pixelfed client.
