### ISSUE TITLE
Add share possibilities from other application to Vernissage

### ISSUE THREAD

**Issue by mczachurski** [VernissageApp/Vernissage#13]
Add share possibilities from other application to Vernissage

**Comment by mczachurski** [comment]
Implemented feature/share-extension

**Comment by xabirequejo** [comment]
I'm using Vernissage 1.2.0 (102) on iOS 16.3.1 and I don't see this option.
When selecting a picture I can share it with some apps, but Vernissage is not one of them. I cannot reproduce [this video](https://mastodon.social/@vernissage/110163817445438327). I have also checked the suggested apps but Vernissage is nowhere to be found.
I have removed and installed the app again. I have also restarted my phone.
Am I doing something wrong?

**Comment by xabirequejo** [comment]
I have tried it before and after today's update, restarting my phone, even removing the app and installing it again but I still don't see Vernissage on the share sheet. 🤨
