### ISSUE TITLE
Notifications and comments showing 0 seconds always

### ISSUE THREAD

**Issue by orangemelo11** [VernissageApp/Vernissage#17]
Hi,

first of all congrats on your new app and wonderful interface keep going!!

I found this notification bug which shows 0 seconds always wrong timing on the notifications bar and I suggest notification panel has to be better.

![IMG_0035](https://user-images.githubusercontent.com/119735594/230497568-b18f67ca-0a36-4cf0-adbe-1359d7604ab6.png)

and here is the comment section 
![IMG_0036](https://user-images.githubusercontent.com/119735594/230498138-767d64f9-12d3-4ac5-9859-4b5908e9e95c.jpeg)

**Comment by mczachurski** [comment]
Now instead of showing seconds we will have title: 'moments ago'. Also we can increments seconds on that views, but I'm not sure that this is so important, maybe that string is enough.

**Comment by orangemelo11** [comment]
> Now instead of showing seconds we will have title: 'moments ago'. Also we can increments seconds on that views, but I'm not sure that this is so important, maybe that string is enough.

Trust me it’s important to have correct timings and time lapses it shows how prominent the app is.

I have been looking for an update on the AppStore I guess it might take some time to get the update looking for the best

thanks

**Comment by mczachurski** [comment]
I agree with you. Sometimes we need more motivation ;-). 

There will be a new version in a few days when I finish other things as well.

**Comment by orangemelo11** [comment]
I’ll support you soon give me sometime
