### ISSUE TITLE
Better Alt Text Design

### ISSUE THREAD

**Issue by Suzie97** [VernissageApp/Vernissage#23]
# Problem
Right now, if the "Show alternative text" option is turned on in the app settings, it takes up a significant amount of space in the UI. This is particularly a bigger problem if the alt text is too long.

### Short Alt Text
![D5C4B6A4-B688-4AFE-98BB-1CB31EB896C9_1_201_a](https://user-images.githubusercontent.com/68198116/230731310-d8ac3521-2eac-4dbc-bc45-4d17d9145f29.jpeg)

### Long Alt Text
![29A7DC10-6EB8-4090-A4A1-7D4C07E0A5A7_1_105_c](https://user-images.githubusercontent.com/68198116/230731180-542ca802-eb75-4b73-ab31-110e567f59c2.jpeg)

As you can see in the screenshot with the long Alt Text, it takes up quite a lot of space in the UI.

# Proposal
Come up with a better solution that provides the option to view Alt Text without taking too much space in the UI.

# Prior Art
## Elk for Mastodon
<img width="620" alt="Screen Shot 2023-04-08 at 21 46 48" src="https://user-images.githubusercontent.com/68198116/230731809-e5e19daf-e679-4acc-a883-8526d74750dd.png">

**Comment by mczachurski** [comment]
Thank you for the great description! I will try to come up with something better than it currently is.

**Comment by mczachurski** [comment]
I've changed a little bit current behaviour of ALT text:
 - we have a new menu action item ("Show media description") on the timelines (always accessible):

![IMG_4115](https://user-images.githubusercontent.com/6191974/232754691-1295ffcc-94db-4bad-b84a-84aaa1d1183f.PNG) ![IMG_4117](https://user-images.githubusercontent.com/6191974/232754719-228426df-509f-4724-b5ca-af97d6ba83cd.PNG)

 - we have a ALT image button in bottom right corner of each image (for quick access, enabled in the application settings)

![IMG_4114](https://user-images.githubusercontent.com/6191974/232755100-414bf2ee-1f34-41a2-bd31-71aa4f3725dc.PNG)

 - and only first three lines of text are now showed in the status details page and we have "SHOW MORE" button visible for longer descriptions (enabled in the application settings)

![IMG_4116](https://user-images.githubusercontent.com/6191974/232755589-d4afeb8e-e2c3-4552-badd-f8397440b04e.PNG)

What do you think @Suzie97 about that implementation. It's not the same like in the ELK but I don't want to cover the image with any button in the image details page if we have so many other space here ;-).

**Comment by Suzie97** [comment]
> What do you think @Suzie97 about that implementation. It's not the same like in the ELK but I don't want to cover the image with any button in the image details page if we have so many other space here ;-).

@mczachurski thank you so much for working on this issue so quickly. I tried out the new updates in the app, and I like the overall changes. Especially using a dialog for showing alt text rather than hiding the covering the image. Very thoughtful 😉.

Some minor caveats imo are:
- The "Ok" button label on the media description dialog does not make much sense. I think changing it to something like "Close" would make more sense.
- And I don't know if viewing a 3 line preview of the alt text is useful in any contexts. I think alt text should be read entirely. So rather than showing a three line preview, should we hide it by default, say under a button named "Show Media Description" and expand the entire alt text on click?

**Comment by mczachurski** [comment]
Agree with "OK" button 👍. I will leave that 3 line preview (I think in most cases descriptions are shorter). Maybe we can come back to that in the future.
