### ISSUE TITLE
Allow photos to be selected from the files app too

### ISSUE THREAD

**Issue by orangemelo11** [VernissageApp/Vernissage#25]
It’s much better if photos can be selected from the files app too  currently the app allows from the  photos app as an option the files app option should appear 👍🏻

**Comment by mczachurski** [comment]
Photos can be selected from all application which can export images. I've tested this in:
 - Photos
 - Files
 - Dropbox.

**Comment by orangemelo11** [comment]
@mczachurski  could you show me how to do this on the app?  
![Uploading IMG_0066.jpeg…]()

**Comment by mczachurski** [comment]
Ok, now I know what you mean. What I meant was that you can open the Files app, find the photo and click share. Vernissage then appears in the list. If you think that it's not enough you can reopen the issue 👍

**Comment by mczachurski** [comment]
Implemented as on of three choices in the compose screen:

![IMG_4123](https://user-images.githubusercontent.com/6191974/233860510-3ffe3231-4612-45b9-a407-3f7d7397145d.PNG)

Very similar to other social applications.
