### ISSUE TITLE
Request to resize all images to same size and also show number of comments and likes while scrolling + image comments to not showing 

### ISSUE THREAD

**Issue by orangemelo11** [VernissageApp/Vernissage#29]
It would be cool if every images can be resized to a certain decent size and not let larger images appear on the app I hope you got what I mean? Larger images on the app is kinda ugly or not looking better it would be better if all images can be resized to a certain decent image size.

plus while scrolling it would be better if it could be shown at the bottom of the image how many likes and comments has the post has received 

Bottom part

this is a big image comments does not show on the app

final thoughts it please consider updating real time comments example if i comment on a post now it should show at the same time

**Comment by mczachurski** [comment]
I'm not sure that resizing image is a good idea. I don't know what is "decent size". We can have horizontal or vertical image (16:9, 16:40, 4:3, 2:3, 1:1 etc.). I cannot predict one size good for all of them. If I will cut the image then you will have to open details of each image to check what has been cut. And that will have big impact of your experience.

On timeline I will show favourite star (and user avatar and display name). The rest of the data will be on the image details screen.

Your new comments should be automatically visible in comments section. I will verify this.

**Comment by orangemelo11** [comment]
> I'm not sure that resizing image is a good idea. I don't know what is "decent size". We can have horizontal or vertical image (16:9, 16:40, 4:3, 2:3, 1:1 etc.). I cannot predict one size good for all of them. If I will cut the image then you will have to open details of each image to check what has been cut. And that will have big impact of your experience.
> 
> On timeline I will show favourite star (and user avatar and display name). The rest of the data will be on the image details screen.
> 
> Your new comments should be automatically visible in comments section. I will verify this.

I suggest 16:9 aspect ratio as the decent size for all images 

attaching an image

**Comment by mczachurski** [comment]
For now I will close the issue, the current behaviour is good.
Part with automatically visible comments is registered in other issuer and it will be investigated and fixed: #19.
