### ISSUE TITLE
Supporting stories

### ISSUE THREAD

**Issue by xplosionmind** [VernissageApp/Vernissage#39]
This app is way better than the official one, and it lacking support for stories constitutes the greatest limit for me!

**Comment by BarterClub** [comment]
Yes please

**Comment by fishcharlie** [comment]
@mczachurski Why is this marked as working as intended?

**Comment by mczachurski** [comment]
The application was designed with the primary focus on displaying photos. Other media types, such as videos, stories, and similar content, were not a priority during the development process.

**Comment by fishcharlie** [comment]
@mczachurski Would you accept PR(s) to implement those features or not?
