### ISSUE TITLE
Add Swipe actions in timeline

### ISSUE THREAD

**Issue by Suzie97** [VernissageApp/Vernissage#51]
Using swipe actions to favourite, boost, reply and bookmark posts in the timeline would be nice and faster than holding the post to open the context menu :)

**Comment by mczachurski** [comment]
Agree. But how this would work when we have more than one photo and we have carousel (and left/right swipes switches between photos)?

**Comment by Suzie97** [comment]
> Agree. But how this would work when we have more than one photo and we have carousel (and left/right swipes switches between photos)?

I think swipe actions will not interfere with the current behaviour. 

Right now, when people try to swipe when they are already on the first or last photo in the carousel, the feedback that they can't swipe to view more pictures is provided through the empty space and the rubberbanding effect.

If swipe actions are added, the black space will just be replaced by actions (like favourite, boost), and the feedback about the end of the carousel will still be communicated.

**Comment by mczachurski** [comment]
Unfortunately system (and SwiftUI Framework) is not so smart to figure out what we want to do and carousel swipes overrides left/right swipes which we have in the list row. Thus we can swipe images without carousel, but when we have carousel then we can switch only between pictures. To achieve what you described we would have to create that whole mechanism from the scratch or do some workarounds. And I'm not sure that it's worth it 🤔.

**Comment by Suzie97** [comment]
> And I'm not sure that it's worth it 🤔.

Hmm, personally I think the swipe features would be neat. 

If we do a mastodon poll, can we rely on the results to see if enough people want this? At the very least, it'll give us a rough idea if people find it useful or not.

**Comment by mczachurski** [comment]
But people won't think of all the issues just the general idea. And I agree that in general swipe left/right to access the actions panel is very good. But not in our example where we already have these swipes in the carusel. Swiping across all the images in the carusel to get to the action menu is not elegan solution. Let's imagine that in some of the instances users can add 10 images, and if someone wants to use action menu they have to swipe eleven times. Also then we can only have that swipe gesture on one side (I can't imagine someone swiping several times and then swiping again to access actions on the left).

Also I tried to figure out how to implement that kind of thing from a technical point of view. But I don't have any good idea.

The last reason that this is not a good idea (in our example on the timelines) is future development. In the iPad version of the application I would like to have grid with images, somthing like that:

<img width="375" alt="gird" src="https://user-images.githubusercontent.com/6191974/233821071-e6e2e476-70a1-4622-af5c-675f60bb7625.png">

And in that layout it would be even harder implament that kind of interaction. We can have swipe action menu in other places (like comments, notifications etc., places where we don't have carousel).

For now I'm really sorry but I will close the issue, however thank you for your feedback 👍.
