### ISSUE TITLE
Feature request: prompt for ALT text

### ISSUE THREAD

**Issue by xabirequejo** [VernissageApp/Vernissage#59]
Right now the option to add a description to the pictures feels hidden.

Due to the particularities of the Fediverse, I believe adding descriptions should be encouraged, that is why maybe this option could be moved to a more visible area requiring less taps or even prompt user to add a description before publishing.

**Comment by mczachurski** [comment]
Yes, indeed it would be better if that option will be mote visible somehow. At the moment I have no idea how to change it but I will think of something.

**Comment by mczachurski** [comment]
I'm working right now on drag&drop images feature. And it seems that this is not working when I have `Menu` plugged in to image 🤨. Thus, I will have to figure out something different for `Delete`/`Preview` actions. Perhaps you have an idea?

https://user-images.githubusercontent.com/6191974/234931587-26edd5c7-1110-4302-97be-93288fdb186f.mp4

**Comment by mczachurski** [comment]
For now I have something like that:

![Simulator Screenshot - iPhone 14 Pro - 2023-04-28 at 08 25 13](https://user-images.githubusercontent.com/6191974/235071042-33f69c32-b914-4a18-8d3a-3445d8e1ac49.png)

There is not menu. User can reorder images, delete directly by tapping "X" icon, and tap on the image to edit ALT text. Also there is an information which images already have ALT texts.

**Comment by xabirequejo** [comment]
I like it, and I also like [the image you shared on Mastodon](https://social.vivaldi.net/@vernissage@mastodon.social/110275653374159979), either would be an improvement.
Maybe, just maybe, I'd change the red dot for a yellow triangle ⚠️ if that's the design you go for.
And maybe I'd add an option in the settings to force me to add ALT text.

**Comment by mczachurski** [comment]
Feature implemented. We can reorder images, we have information about missing ALT texts and settings when we can decide if we want to have warning (and information on images) about missing ALT texts.
