### ISSUE TITLE
Click on the number of new post does nothing

### ISSUE THREAD

**Issue by tehabe** [VernissageApp/Vernissage#91]
When new posts are detected you get a number in the top right corner.

![number](https://github.com/VernissageApp/Vernissage/assets/67130363/955fb7b1-07b4-40f6-badf-5244226d583e)

To get the new posts you have to pull the feed, intuitive clicking on the number, like on Ice Cubes, does not load the new posts. My suggestion would be, that it behaves like in Ice Cubes, it doesn't go straight to the top but loads one page after the other new available posts.

**Comment by mczachurski** [comment]
At this time, the new photo counter is displayed for informational purposes only. I do not intend to make any changes to this functionality at the moment.
